boss:
  customCityCode: {珠海: '101280700', 佛山: '101280800'}
  keywords: [Java]
  h5Jobs: false
  cityCode: [广州]
  apiDomain: https://9d09-120-85-107-188.ngrok-free.app
  debugger: false
  keyFilter: false
  degree: [本科]
  scale: [不限]
  industry: [不限]
  enableAI: true
  experience: [5-10年]
  salary: 10-20K
  checkStateOwned: false
  sayHi: |
    您好，我具备多年 Java Web 开发经验，完整经历从 JSP/Servlet 到 SSM（Spring + Spring MVC + MyBatis），再到 Spring Boot / Spring Cloud 微服务架构的演进过程，熟悉系统拆分、服务治理、配置中心、链路追踪等核心组件；掌握 Redis、Kafka、Nacos、Docker、Jenkins 等中间件与持续集成运维工具，具备微服务系统的全流程开发与交付能力。
    前端方面，经历了从传统 HTML/CSS/JavaScript 开发，到 jQuery、Bootstrap 样式框架、ExtJS 富客户端框架，再到现代 Vue + Element-UI 的组件化开发模式，熟悉前后端分离架构与 RESTful API 调用，能够独立完成页面交互、组件封装及联调工作。
    参与过支付、商城、物流仓储、订单中心等系统，具备持续集成及运维能力。独立完成需求、完成系统设计及开发实现，也具备任务拆解与团队协作推进能力。
  filterDeadHR: true
  stage: [不限]
  vipKey: zhangk
  deadStatus: [2周内活跃, 本月活跃, 3月内活跃, 2月内活跃, 半年前活跃]
  sendImgResume: true
  resumeImagePath: D:\Users\zhang\IdeaProjects\npe_get_jobs\src\main\resources\resume.jpg
  recommendJobs: false
  expectedSalary: [15, 25]
  jobType: 全职
  waitTime: 10
h5boss:
  keywords: [Java]
  cityCode: [广州]
  customCityCode: {佛山: c101280800, 珠海: c101280700}
  experience: [5-10年]
  salary: 10-20K
  degree: [本科]
  scale: [不限]
job51:
  jobArea: [上海]
  keywords: [java, python, go, golang, 大模型, 软件工程师]
  salary: [不限]
lagou:
  keywords: [AI工程师, Java, Golang, Python]
  cityCode: 上海
  salary: 不限
  scale: [不限]
  gj: 在校/应届,3年及以下
liepin:
  cityCode: 上海
  keywords: [Java, Python, Golang, 大模型]
  salary: 15$30
zhilian:
  cityCode: 上海
  salary: 25001,35000
  keywords: [AI, Java, Python, Golang]
ai: {introduce: 我熟练使用Spring Boot、Spring Cloud、Alibaba Cloud及其生态体系，擅长MySQL、Oracle、PostgreSQL等关系型数据库以及MongoDB、Redis等非关系型数据库。熟悉Docker、Kubernetes等容器化技术，掌握WebSocket、Netty等通信协议，拥有即时通讯系统的开发经验。熟练使用MyBatis-Plus、Spring
    Data、Django ORM等ORM框架，熟练使用Python、Golang开发，具备机器学习、深度学习及大语言模型的开发与部署经验。此外，我熟悉前端开发，涉及Vue、React、Nginx配置及PHP框架应用,
  prompt: '我目前在找工作,%s,我期望的的岗位方向是【%s】,目前我需要投递的岗位名称是【%s】,这个岗位的要求是【%s】,如果这个岗位和我的期望与经历基本符合，注意是基本符合，那么请帮我写一个给HR打招呼的文本发给我，如果这个岗位和我的期望经历完全不相干，直接返回false给我，注意只要返回我需要的内容即可，不要有其他的语气助词，重点要突出我和岗位的匹配度以及我的优势，我自己写的招呼语是：【%s】,你可以参照我自己写的根据岗位情况进行适当调整'}
bot: {is_send: true}
